const Translations = {
    en: {
        loginSuccessMessage: 'Login Successful',
        loginFailedMessage: 'Login failed',
        signIn: 'Sign in',
        resetPassword: 'Reset password',
        activateUser: 'Activate user',
        emailAddress: 'Email address',
        enterYourEmail: 'Enter your email',
        userIsAlreadyActive: 'User is already active',
        enterYourPassword: 'Enter your password',
        invalidEmail: 'Invalid email address',
        password: 'Password',
        userNotActive: 'User not active',
        wrongEmail: 'Wrong email',
        setNewPassword: 'Set new password',
        sendVerificationEmail: 'Send verification email',
        sendedVerificationEmail: 'Verification email sent',
        returnToSignInPage: 'Return to sign-in page',
        anErrorAccured: 'An error accured',
        successfull: 'Successfull',
        alreadyHaveAnAccount: 'I already have an account',
        name: 'Name',
        surname: 'Surname',
        role: 'Role',
        addPhoto: 'Add photo',
        department: 'Department',
        email: 'Email',
        company: 'Company',
        userInfo: 'User Information',
        signOut: 'Sign out',
        menu: 'Menu',
        home: 'Home',
        users: 'Users',
        companies: 'Companies',
        cities: 'Cities',
        regions: 'Regions',
        Add: 'Add',
        Delete: 'Delete',
        Edit: 'Edit',
        towns: 'Towns',
        addUser: 'Add user',
        addPhoto: 'Add photo',
        addCompany: 'Add company',
        addCity: 'Add city',
        addRegion: 'Add region',
        addTown: 'Add town',
        shortName: 'Short name',
        companyType: 'Company type',
        street: 'Street',
        userAdded: 'User added',
        photoAdded: 'Photo added',
        companyAdded: 'Company added',
        townAdded: 'Town added',
        regionAdded: 'Region added',
        cityAdded: 'City added',
        userEdited: 'User edited',
        companyEdited: 'Company edited',
        townEdited: 'Town edited',
        regionEdited: 'Region edited',
        cityEdited: 'City edited',
        userDeleted: 'User deleted',
        companyDeleted: 'Company deleted',
        townDeleted: 'Town deleted',
        regionDeleted: 'Region deleted',
        cityDeleted: 'City deleted',
        wrongEmailOrPassword: 'Wrong email or password',
        wrongEmail: 'Wrong email',
        addressStreet: 'Street',
        addressTown: 'Town',
        region: 'Region',
        city: 'City'

    },
    tr: {
        loginSuccessMessage: 'Giriş Başarılı',
        loginFailedMessage: 'Giriş başarısız',
        enterYourEmail: 'E-posta adresinizi girin',
        enterYourPassword: 'Şifrenizi girin',
        signIn: 'Giriş yap',
        resetPassword: 'Şifreyi sıfırla',
        successfull: 'Başarılı',
        activateUser: 'Kullanıcıyı etkinleştir',
        emailAddress: 'E-posta adresi',
        Add: 'Ekle',
        userNotActive: 'Kullanıcı aktif değil',
        wrongEmail: 'Yanlış e-posta',
        Delete: 'Sil',
        Edit: 'Düzenle',
        anErrorAccured: 'Bir hata oluştu',
        invalidEmail: 'Geçersiz e-posta adresi',
        password: 'Şifre',
        sendVerificationEmail: 'Doğrulama e-postası gönder',
        sendedVerificationEmail: 'Doğrulama e-postası gönderildi',
        returnToSignInPage: 'Giriş sayfasına geri dön',
        alreadyHaveAnAccount: 'Zaten hesabım var',
        name: 'İsim',
        surname: 'Soyisim',
        role: 'Rol',
        department: 'Departman',
        company: 'Şirket',
        email: 'E-posta',
        userIsAlreadyActive: 'Kullanıcı zaten aktif',
        userInfo: 'Kullanıcı Bilgisi',
        signOut: 'Çıkış yap',
        menu: 'Menü',
        home: 'Ana Sayfa',
        users: 'Kullanıcılar',
        companies: 'Şirketler',
        cities: 'Şehirler',
        setNewPassword: 'Yeni şifre belirle',
        regions: 'Bölgeler',
        towns: 'Kasabalar',
        addUser: 'Kullanıcı ekle',
        addPhoto: 'Fotoğraf ekle',
        addCompany: 'Şirket ekle',
        addCity: 'Şehir ekle',
        addRegion: 'Bölge ekle',
        addTown: 'Kasaba ekle',
        shortName: 'Kısa ad',
        companyType: 'Şirket tipi',
        addPhoto: 'Fotoğraf ekle',
        street: 'Cadde',
        userAdded: 'Kullanıcı eklendi',
        photoAdded: 'Fotoğraf eklendi',
        companyAdded: 'Şirket eklendi',
        townAdded: 'Kasaba eklendi',
        regionAdded: 'Bölge eklendi',
        cityAdded: 'Şehir eklendi',
        userEdited: 'Kullanıcı düzenlendi',
        companyEdited: 'Şirket düzenlendi',
        townEdited: 'Kasaba düzenlendi',
        regionEdited: 'Bölge düzenlendi',
        cityEdited: 'Şehir düzenlendi',
        userDeleted: 'Kullanıcı silindi',
        companyDeleted: 'Şirket silindi',
        townDeleted: 'Kasaba silindi',
        regionDeleted: 'Bölge silindi',
        cityDeleted: 'Şehir silindi',
        wrongEmailOrPassword: 'Yanlış e-posta veya şifre',
        wrongEmail: 'Yanlış e-posta',
        addressStreet: 'Mahalle',
        region: 'Bölge',
        addressTown: 'İlçe',
        city: 'Şehir'
    }
};

export default Translations;
