const translations = {
    en: {
        'Login Successfull': 'Login Successful',
        'login failed': 'Login failed',
        'Sign in': 'Sign in',
        'Reset password': 'Reset password',
        'activate user': 'Activate user',
        'e mail address': 'Email address',
        'password': 'Password',
        'send verification e mail': 'Send verification email',
        'return in sign in page': 'Return to sign-in page',
        'I already have an account': 'I already have an account',
        'name': 'Name',
        'surname': 'Surname',
        'role': 'Role',
        'department': 'Department',
        'user information': 'User information',
        'sign out': 'Sign out',
        'menu': 'Menu',
        'home': 'Home',
        'users': 'Users',
        'companies': 'Companies',
        'cities': 'Cities',
        'regions': 'Regions',
        'towns': 'Towns',
        'add user': 'Add user',
        'add photo': 'Add photo',
        'add company': 'Add company',
        'add city': 'Add city',
        'add region': 'Add region',
        'add town': 'Add town',
        'short name': 'Short name',
        'company type': 'Company type',
        'street': 'Street',
        'user added': 'User added',
        'photo added': 'Photo added',
        'company added': 'Company added',
        'town added': 'Town added',
        'region added': 'Region added',
        'city added': 'City added',
        'user edited': 'User edited',
        'company edited': 'Company edited',
        'town edited': 'Town edited',
        'region edited': 'Region edited',
        'city edited': 'City edited',
        'user deleted': 'User deleted',
        'company deleted': 'Company deleted',
        'town deleted': 'Town deleted',
        'region deleted': 'Region deleted',
        'city deleted': 'City deleted',
        'wrong email or password': 'Wrong email or password',
        'wrong email': 'Wrong email'
    },
    tr: {
        'Login Successfull': 'Giriş Başarılı',
        'login failed': 'Giriş başarısız',
        'Sign in': 'Giriş yap',
        'Reset password': 'Şifreyi sıfırla',
        'activate user': 'Kullanıcıyı etkinleştir',
        'e mail address': 'E-posta adresi',
        'password': 'Şifre',
        'send verification e mail': 'Doğrulama e-postası gönder',
        'return in sign in page': 'Giriş sayfasına geri dön',
        'I already have an account': 'Zaten hesabım var',
        'name': 'İsim',
        'surname': 'Soyisim',
        'role': 'Rol',
        'department': 'Departman',
        'user information': 'Kullanıcı bilgisi',
        'sign out': 'Çıkış yap',
        'menu': 'Menü',
        'home': 'Ana Sayfa',
        'users': 'Kullanıcılar',
        'companies': 'Şirketler',
        'cities': 'Şehirler',
        'regions': 'Bölgeler',
        'towns': 'Kasabalar',
        'add user': 'Kullanıcı ekle',
        'add photo': 'Fotoğraf ekle',
        'add company': 'Şirket ekle',
        'add city': 'Şehir ekle',
        'add region': 'Bölge ekle',
        'add town': 'Kasaba ekle',
        'short name': 'Kısa ad',
        'company type': 'Şirket tipi',
        'street': 'Cadde',
        'user added': 'Kullanıcı eklendi',
        'photo added': 'Fotoğraf eklendi',
        'company added': 'Şirket eklendi',
        'town added': 'Kasaba eklendi',
        'region added': 'Bölge eklendi',
        'city added': 'Şehir eklendi',
        'user edited': 'Kullanıcı düzenlendi',
        'company edited': 'Şirket düzenlendi',
        'town edited': 'Kasaba düzenlendi',
        'region edited': 'Bölge düzenlendi',
        'city edited': 'Şehir düzenlendi',
        'user deleted': 'Kullanıcı silindi',
        'company deleted': 'Şirket silindi',
        'town deleted': 'Kasaba silindi',
        'region deleted': 'Bölge silindi',
        'city deleted': 'Şehir silindi',
        'wrong email or password': 'Yanlış e-posta veya şifre',
        'wrong email': 'Yanlış e-posta'
    }
};

export default translations;
